# Uncomment the next line to define a global platform for your project
 platform :ios, '15.2'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'MyPokedex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyPokedex
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'MyPokedexUnitTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

end
